clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - master

configuration: Release

build:
  project: MarkdownLog.sln

test: auto

after_test:
  - cmd: dotnet pack MarkdownLog\ -c Release
