#version should be changed with any pull requests
version: 0.10.0

clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - master

configuration: Release

build:
  project: MarkdownLog.sln

test: auto

after_test:
  - cmd: dotnet pack MarkdownLog/ -c Release

artifacts:
  - path: 'MarkdownLog/bin/Release/*.nupkg'

deploy:
 provider: NuGet
 api_key:
   secure: n/2gZwCGLcoLBr5nGu5akS0IFQ1YHciI6Wz0NGC+1mLTUtO08Uy+TWn7OtyLG9v3
 artifact: /.*\.nupkg/
  
  
  